### PR TITLE
Fix the bullet points in the readme

### PR DESCRIPTION
**Pull request by erbridge**

### CODE REVIEW

**Comment by 0x0ade** [comment]
Huh, I didn't know that `*` didn't work for some. Thank you!

**Comment by erbridge** [comment]
Honestly I don't really understand why the parser is all confused, and clearly something is still messing with it..

**Comment by 0x0ade** [comment]
It seems like replacing the spaces fixed the issue. I'll just blame my mobile keyboard (had to update README.md from my phone yesterday) ¯\\\_(ツ)\_/¯

**Comment by erbridge** [comment]
Odd. Wonder maybe your mobile keyboard likes nbsp...

**Pull request merged**
